### PR TITLE
Update owners to have a dspo rep as approver.

### PR DESCRIPTION
**Pull request by HumairAK**
## Description
It probably makes sense to have one of the dspo component owners to be able to dev-approve prs pertaining to DSPO/DSP. 

cc @accorvin 

## How Has This Been Tested?
No code change.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.

The following does not apply as this is not a code change.

- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [ ] JIRA link(s):
- [ ] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Review by anishasthana — CHANGES_REQUESTED** [review]
Can you keep the correct ordering of names?

**Review by zdtsw — COMMENTED** [review]
think we should not have pablofelix for QE any more

FYI  @pablofelix

**Review by zdtsw — APPROVED** [review]

**Review by anishasthana — APPROVED** [review]
/lgtm

**Review by tarukumar — APPROVED** [review]
/lgtm.  @HumairAK  could you add one more qe who is from Europe in the list so that you guys do not wait for me for the approvals if i am not around due to time differences. May be @jgarciao

**Comment by HumairAK** [comment]
done

**Review by anishasthana — COMMENTED** [review]
/lgtm

**Pull request merged**
