### PR TITLE
Remove ViewerCRD image parameter from Kfdef

### PR DESCRIPTION
**Pull request by rimolive**
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [ ] JIRA link(s):
- [ ] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Comment by HumairAK** [comment]
@jgarciao can we get qe approval to merge this

**Review by HumairAK — APPROVED** [review]

**Comment by jgarciao** [comment]
LGTM

**Pull request merged**
