### PR TITLE
Update Pytorch and Tensorflow images

### PR DESCRIPTION
**Pull request by VaishnaviHire**
## How Has This Been Tested?
The feature has been tested as part of PRs : https://github.com/red-hat-data-services/s2i-pytorch-notebook/pull/9, https://github.com/red-hat-data-services/s2i-tensorflow-gpu-notebook/pull/11

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [x] JIRA link(s): Related issue: https://issues.redhat.com/browse/RHODS-2978
- [x] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Comment by lugi0** [comment]
@VaishnaviHire is this just pointing to the updated images (pytorch/tensorflow) from the other PRs?

**Comment by VaishnaviHire** [comment]
> @VaishnaviHire is this just pointing to the updated images (pytorch/tensorflow) from the other PRs?

Yes. Following are the tagged branches

https://github.com/red-hat-data-services/s2i-pytorch-notebook/tree/nb-5 
https://github.com/red-hat-data-services/s2i-tensorflow-gpu-notebook/tree/nb-6

**Review by lugi0 — APPROVED** [review]
thanks, lgtm

**Review by samuelvl — APPROVED** [review]
/lgtm

**Pull request merged**
