### PR TITLE
Fix issue deploying starbust

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Fix issue with starbust deployment on prem

## How Has This Been Tested?

No testing provided, please someone verify this

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [X] JIRA link(s): https://issues.redhat.com/browse/RHODS-6940
- [X] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Review by zdtsw — APPROVED** [review]
/lgtm

**Comment by lucferbux** [comment]
@bdattoma Can you take a look, not sure what acks it needs

**Comment by lucferbux** [comment]
@anishasthana @VaishnaviHire @LaVLaS could you check this out? I'm aiming to merge this before feature freeze, thanks in advance!

**Comment by zdtsw** [comment]
> @anishasthana @VaishnaviHire @LaVLaS could you check this out? I'm aiming to merge this before feature freeze, thanks in advance!

Can we get this reviewed by this week so we can build it next Monday? Thanks!

**Pull request merged**
