### PR TITLE
Change overlay of dashboard kfdef

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Change the overlay of the dashboard release based on https://github.com/opendatahub-io/odh-dashboard/pull/1622

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [x] JIRA link(s):
- [ ] The Jira story is acked.
- [x] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Comment by lucferbux** [comment]
This should be merged after https://github.com/red-hat-data-services/odh-manifests/pull/446

**Review by zdtsw — COMMENTED** [review]
/lgtm


aim for 1.32 release

**Comment by lucferbux** [comment]
@andrewballantyne @vaibhavjainwiz @zdtsw Same thing here, it's now ready for 1.33

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Pull request merged**
