### PR TITLE
Remove KFNBC Migration code

### PR DESCRIPTION
**Pull request by VaishnaviHire**
## How Has This Been Tested?
1. Upgrade from 1.16 to 1.17
      - Fresh install of RHODS 1.16
      - Upgrade to live-build (quay.io/modh/rhods-operator-live-catalog:1.17.0-rhods-5000)
      - Test if upgrade is successful 

3. Upgrade from 1.15 --> 1.16--> 1.17
      - Upgrade from  RHODS 1.15 --> RHODS 1.16
      - Upgrade to live-build (quay.io/modh/rhods-operator-live-catalog:1.17.0-rhods-5000)
      -  Test if alll CRO resources are deleted and upgrade is successful.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-5000 
- [x] The Jira story is acked.
- [x] Live build image: quay.io/modh/rhods-operator-live-catalog:1.17.0-[rhods-5000](https://issues.redhat.com//browse/rhods-5000)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
@pablofelix @LaVLaS Dockerfile changes are also reflected in this MR https://gitlab.cee.redhat.com/data-hub/rhods-live-builder/-/merge_requests/42

**Comment by LaVLaS** [comment]
Tested this by upgrading from 1.15 to 1.17 inthis livebuild.  It did remove Postgres and recover automatically when the RDS delete was stalled due to a SnapShot quota issue.  The only issue was that JH is left in an error state due to the jupyterhub-rds-secret being removed

@VaishnaviHire Correct me if I am wrong but is 1.16 being skipped for the managed service so any RHODS installs on OSD will have an upgrade path of 1.15 (JupyterHub) -> 1.17? If so, this PR removes the migration from JH -> KFNBC so JH will never be removed?

**Comment by cfchase** [comment]
We are not skipping 1.16.  All managed cloud customers will still install 1.16.  1.17 will be released to production a few  hours afterwards.

**Comment by VaishnaviHire** [comment]
As Chris mentioned, the upgrade path would be 1.15 --> 1.6 --> 1.7

For testing it,

I first upgraded from 1.15 --> 1.16, then
upgraded from 1.16 --> 1.17 .For this upgrade, we would also need to update the `replaces` field in csv

**Comment by LaVLaS** [comment]
/lgtm

@VaishnaviHire @cfchase Thx for the clarification

**Review by LaVLaS — APPROVED** [review]
/lgtm

This worked for me. When testing an upgrade

**Review by anishasthana — COMMENTED** [review]
/lgtm

**Comment by VaishnaviHire** [comment]
Tide is pending due to absence of `qe-approved` label

**Review by pablofelix — COMMENTED** [review]
/lgtm

**Pull request merged**
