### PR TITLE
[Do not merge] Test RHODS live builder

### PR DESCRIPTION
**Pull request by samuelvl**
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-2108 RHODS-2659
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Comment by anishasthana** [comment]
@samuelvl do we need to keep this PR open?

**Comment by aloganat** [comment]
Hi @anishasthana , Is it okay that we keep this PR open? I have requested Samu to have this dummy PR to check the pr validation job from jenkins.

**Review by anishasthana — COMMENTED** [review]
Yep, sounds good!

**Comment by samuelvl** [comment]
Closing PR.

**Pull request closed without merging**
