### PR TITLE
Add Kfdef and Prometheus configuration for Modelmesh monitoring

### PR DESCRIPTION
**Pull request by rimolive**
Signed-off-by: Ricardo Martinelli de Oliveira <rmartine@redhat.com>

## Description
Add the kfdef to deploy modelmesh, as well as the monitoring configuration for Prometheus

## How Has This Been Tested?
* Deploy RHODS
* Open Prometheus endpoint
* In the Status > Targets menu, you should see the following:
    * Modelmesh Controller (1/1 up)
    * ODH Model Controller (3/3 up)

## Merge criteria:
PR https://github.com/red-hat-data-services/odh-manifests/pull/255 must be merged before testing.

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [X] JIRA link(s): https://issues.redhat.com/browse/RHODS-5433
- [X] The Jira story is acked.
- [ ] Live build image: 
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Comment by rimolive** [comment]
@lugi0 This PR was tested in both scenarios:
* Upgrading from an older release
* Installation from scratch

Let me know if you are ok with this.

P.S.: @anishasthana told me to ping you about this PR.

**Comment by lugi0** [comment]
@rimolive @anishasthana there was a doubt initially about either deploying a separate monitoring stack for model serving (or even one stack per model being served) or reusing the rhods monitoring stack.
I take it a decision has been reached and we are moving forward with reusing rhods?

**Comment by anishasthana** [comment]
hey @lugi0, this monitoring stack is for monitoring _infrastructure_ pods for modelmesh monitoring, not models themselves. There will be two monitoring stacks.

1. RHODS monitoring for infra pods (this PR)
2. (wip) Model monitoring stack for deployed models: https://github.com/red-hat-data-services/odh-deployer/pull/266

**Comment by anishasthana** [comment]
Replaced by #266

**Pull request closed without merging**
