### PR TITLE
Remove Grafana from RHODS monitoring stack

### PR DESCRIPTION
**Pull request by anishasthana**
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-3649
- [x] The Jira story is acked.
- [x] Live build image: quay.io/anishasthana/rhods-operator-live-catalog:1.20.1-3649
- [x] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Comment by anishasthana** [comment]
Live build at quay.io/anishasthana/rhods-operator-live-catalog:1.20.1-3649. I'll be testing this out tomorrow

**Review by lucferbux — APPROVED** [review]
/lgtm

**Comment by anishasthana** [comment]
On fresh install

image
image

**Comment by anishasthana** [comment]
Upgrade Testing:
```
./setup.sh quay.io/modh/qe-catalog-source:v1171-1
oc get all -n redhat-ods-monitoring | grep grafana | wc -l
./setup.sh quay.io/anishasthana/rhods-operator-live-catalog:1.20.1-364
```

RHODS 1.17
image

After upgrade:
image
image

**Comment by anishasthana** [comment]
@jgarciao @pablofelix ptal :-)

**Comment by jgarciao** [comment]
Hi @Jooho @anishasthana 

I've tried to install the livebuild over RHODS 1.19.0-14 and got this error (maybe because the livebuild is previous to 1.19?)
image

I'll install 1.17 and try again

**Comment by lucferbux** [comment]
The installation path omits 1.19.0-14, 1.19.0-18 should be installed with 1.18 or earlier to stick to the installation plan. 1.17 should be fine!

**Review by jgarciao — APPROVED** [review]
I was able to install RHODS 1.18.0-9 and then install the livebuild and grafana got removed successfully
```

service "grafana" deleted
route.route.openshift.io "grafana" deleted
Error from server (NotFound): configmaps "grafana" not found
Core Grafana deletion failed
deployment.apps "grafana" deleted
secret "grafana-config" deleted
secret "grafana-proxy-config" deleted
secret "grafana-datasources" deleted
serviceaccount "grafana" deleted
role.rbac.authorization.k8s.io "grafana" deleted
role.rbac.authorization.k8s.io "use-anyuid-scc" deleted
rolebinding.rbac.authorization.k8s.io "grafana-sa-anyuid" deleted
rolebinding.rbac.authorization.k8s.io "grafana-rb" deleted
rolebinding.rbac.authorization.k8s.io "grafana" deleted
Error from server (NotFound): rolebindings.rbac.authorization.k8s.io "grafana-auth-rb" not found
Grafana SA deletion failed
warning: deleting cluster-scoped resources, not scoped to the provided namespace
clusterrolebinding.rbac.authorization.k8s.io "grafana-auth-rb" deleted
```



```
$ oc get all -n redhat-ods-monitoring 
NAME                                     READY   STATUS    RESTARTS   AGE
pod/blackbox-exporter-75b66d54df-g5jdf   2/2     Running   0          9m56s
pod/prometheus-6c9574cc9f-cxnjx          4/4     Running   0          10m

NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/alertmanager        ClusterIP   172.30.25.4      <none>        443/TCP    50m
service/blackbox-exporter   ClusterIP   172.30.234.51    <none>        9114/TCP   50m
service/prometheus          ClusterIP   172.30.142.172   <none>        9091/TCP   49m

NAME                                READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/blackbox-exporter   1/1     1            1           50m
deployment.apps/prometheus          1/1     1            1           49m

NAME                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/blackbox-exporter-75b66d54df   1         1         1       9m57s
replicaset.apps/blackbox-exporter-78c5969f5    0         0         0       50m
replicaset.apps/prometheus-6c9574cc9f          1         1         1       10m
replicaset.apps/prometheus-857cb9f7c6          0         0         0       50m

NAME                                    HOST/PORT                                                               PATH   SERVICES       PORT           TERMINATION          WILDCARD
route.route.openshift.io/alertmanager   alertmanager-redhat-ods-monitoring.apps.rhods-04.rhods.ccitredhat.com          alertmanager   alertmanager   reencrypt/Redirect   None
route.route.openshift.io/prometheus     prometheus-redhat-ods-monitoring.apps.rhods-04.rhods.ccitredhat.com            prometheus     https          reencrypt/Redirect   None
```

**Pull request merged**
