### PR TITLE
Remove CUDA builds

### PR DESCRIPTION
**Pull request by maulikjs**
https://issues.redhat.com/browse/RHODS-1651

### CODE REVIEW

**Review by crobby — APPROVED** [review]

**Comment by anishasthana** [comment]
Aren't the pytorch and tensorflow notebooks that are built here part of the images we _always_ want?

**Review by anishasthana — CHANGES_REQUESTED** [review]
Don't we need to remove https://github.com/red-hat-data-services/odh-deployer/blob/main/deploy.sh#L101?

**Comment by LaVLaS** [comment]
> Aren't the pytorch and tensorflow notebooks that are built here part of the images we _always_ want?

This is a good point. This PR should be paired with another PR to deploy the non-gpu builds for pytorch and tensorflow.  Since we are using the thoth builds for minimal and generic-data-science, is the same pre-built notebook exception allowed  for these non-gpu notebooks?

**Review by crobby — COMMENTED** [review]
I think we just want to remove the build and imagestream for gpu-minimal (cuda)

**Comment by harshad16** [comment]
> Don't we need to remove https://github.com/red-hat-data-services/odh-deployer/blob/main/deploy.sh#L101?

we should remove this as well, as it would break the deployer , if the file is missing.

**Review by crobby — CHANGES_REQUESTED** [review]
So, the newly requested funcitonality via RHODS-1651 is to just remove the annotation from the cuda imagestream so that it will not appear in the spawner UI

**Comment by anishasthana** [comment]
No longer needed.

**Pull request closed without merging**
