### PR TITLE
Add DSP Application recording rules and scrape configs

### PR DESCRIPTION
**Pull request by DharmitD**
Adding Prometheus configuration and recording rules for Data Science Pipelines' Application.

## Description

- Using olminstall, trigger first a clean build with the image `quay.io/rhn_support_ddalvi/rhods-operator-live-catalog:1.25.0-rhods-7876`. Make sure that the installation is successful
- Go to the prometheus instance url in the `redhat-ods-monitoring` namespace, query the recording rules, make sure that they return entries and values relevant to the data science pipelines' application

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-7876
- [x] The Jira story is acked.
- [x] Live build image: quay.io/rhn_support_ddalvi/rhods-operator-live-catalog:1.25.0-rhods-7876
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Comment by jgarciao** [comment]
I've installed livebuild http://quay.io/rhn_support_ddalvi/rhods-operator-live-catalog:1.25.0-rhods-7876 in a cluster and, after creating a DataSciencePipelineApplication, I was able to see the metrics with the query `{job="Data Science Pipelines Application"}`

I have a couple of questions related to this PR that I've asked in this slack thread

livebuild-pr-320-20230414-data-science-pipeline-app-metrics

**Comment by HumairAK** [comment]
the new change is just a rebase after #314 was merged, re-adding labels: 

/lgtm
/approve
/label qe-approve 

(based on  @jgarciao's lgtm above).

**Pull request merged**
