### PR TITLE
Split kfdefs

### PR DESCRIPTION
**Pull request by anishasthana**
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [ ] JIRA link(s):
- [ ] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Comment by anishasthana** [comment]
Live build: quay.io/anishasthana/rhods-operator-live-catalog:1.15.1-4764

**Comment by anishasthana** [comment]
After an upgrade. The kfdefs all look good, and the applications seemed to be stable.
image

**Review by samuelvl — APPROVED** [review]
/lgtm

**Review by VaishnaviHire — COMMENTED** [review]
/lgtm

Worked well in an upgrade path
```
 olminstall % oc get kfdef  --all-namespaces
NAMESPACE                 NAME              AGE
redhat-ods-applications   opendatahub       17m
redhat-ods-applications   rhods-anaconda    91s
redhat-ods-applications   rhods-dashboard   2m20s
redhat-ods-applications   rhods-nbc         2m4s
redhat-ods-monitoring     monitoring        17m
rhods-notebooks           rhods-notebooks   17m
```

**Pull request merged**
