### PR TITLE
Update Prometheus ubi8-minimal images

### PR DESCRIPTION
**Pull request by anishasthana**
1) This updates the ubi8 version to the latest 8.7 image
2) This updates the image registry to registry.redhat.io

The human readable image is registry.redhat.io/ubi8/ubi-minimal:8.7

Jira: https://issues.redhat.com/browse/RHODS-6299

Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

This will need to be sent to the rhods-1.21 branch as well.

Live build image: quay.io/anishasthana/rhods-operator-live-catalog:1.24.0-3649

### CODE REVIEW

**Comment by anishasthana** [comment]
JIRA: https://issues.redhat.com/browse/RHODS-6299

**Comment by anishasthana** [comment]
latest live build: `quay.io/anishasthana/rhods-operator-live-catalog:1.24.0-6299`

**Comment by anishasthana** [comment]
I installed via the `operator` option for olminstall. In the deployer logs:

```
.......
INFO: Applying specific configuration for self-managed environments.
.....
```
No prometheus related logs came up.

Additionally, there are no deployments or pods in the redhat-ods-monitoring namespace
image

**Review by Jooho — APPROVED** [review]
/lgtm

**Comment by anishasthana** [comment]
I installed via the `addon` option for olminstall. In the deployer logs:
```
.......
INFO: Applying specific configuration for OSD environments.
kfdef.kfdef.apps.kubeflow.org/rhods-osd-config created
kfdef.kfdef.apps.kubeflow.org/rhods-osd-config created
Cluster is not for RHODS engineering or test purposes.
service/alertmanager created
route.route.openshift.io/alertmanager created
serviceaccount/prometheus created
secret/prometheus-proxy created
secret/alertmanager-proxy created
secret/prometheus-secret created
route.route.openshift.io/rhods-dashboard created
configmap/prometheus-service-ca created
configmap/prometheus created
configmap/alertmanager created
deployment.apps/prometheus created
persistentvolumeclaim/prometheus-data created
persistentvolumeclaim/alertmanager-data created
service/prometheus created
serviceaccount/prometheus-reader created
route.route.openshift.io/prometheus created
clusterrolebinding.authorization.openshift.io/prometheus-scraper created
clusterrole.rbac.authorization.k8s.io/prometheus-scraper created
rolebinding.rbac.authorization.k8s.io/rhods-prometheus-viewer created
service/blackbox-exporter created
deployment.apps/blackbox-exporter created
configmap/blackbox created
secret/model-serving-etcd created
secret/etcd-passwords created
secret/odh-segment-key created
......
```
Additionally, pods and deployments _are_ being created in redhat-ods-monitoring

image

**Comment by anishasthana** [comment]
@jgarciao fyi^^

**Pull request merged**
