### PR TITLE
refactor: addition of codeflare components as scrape targets and availabil…

### PR DESCRIPTION
**Pull request by dimakis**
…ity alerts

Adding of kuberay, codeflare and mcad components as scrape targets for the prometheus deployment.
Addition of `up` alert for the each component pod.

The SOPs for each component are in [this PR](https://gitlab.cee.redhat.com/dsaridak/managed-tenants-sops/-/merge_requests/1)

MCAD and CodeFlare components need to expose metrics endpoint before the alerts are passing. 
With this PR, Prometheus is actively looking for the pods and the alerts fire.

DO NOT MERGE UNTIL WORK IS CARRIED OUT IN MCAD AND CODEFLARE

## How Has This Been Tested?

Tested on an OSD cluster with the RHODS addon.
Kill the kuberay-operator pods, and watch the alert fire in the prometheus UI. (don't forget to scale down the codeflare and rhods operators)
Once these changes are there, the prometheus deployment must be restarted.

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [ ] JIRA link(s):
- [ ] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Comment by lucferbux** [comment]
@dimakis there's something weird with the commit history in your PR, did you branch out of main?

**Comment by dimakis** [comment]
> @dimakis there's something weird with the commit history in your PR, did you branch out of main?

ah I messed up and accidentally committed deadman snitch and PD keys, so I had to go through the steps that SRE gave me to change the history

**Comment by asm582** [comment]
If I understand this PR, this PR will check the status of the MCAD application, MCAD is launched via KAR controller, the question then would be how does the App know if it's working or not?

**Comment by dimakis** [comment]
> If I understand this PR, this PR will check the status of the MCAD application, MCAD is launched via KAR controller, the question then would be how does the App know if it's working or not?

Yes, it'll just check the availability is all really. It's the bare minimum SRE requirement for release. I've got a doc which outlines a more detailed SLI/SLO metric plan to be introduced later but we're just starting at the basic level to implement then building on top of that.

**Comment by ChristianZaccaria** [comment]
I added a [commit](https://github.com/red-hat-data-services/odh-deployer/pull/365/commits/b1aeb71c7b10c386d7fff7ad594c0cddb4bbcef1) to this PR with additional rules involving SLO alerts for MCAD and CodeFlare Operator. You will find several `probe_success:burnrate` recording rules and alerting rules. Added 3 alerts for each component based on the error budget burn rate. These were based off the way [Data Science Pipelines Operator](https://github.com/red-hat-data-services/odh-deployer/blob/6780553dd3b643bd30db148002a7c8e106905a53/monitoring/prometheus/prometheus-configs.yaml#L239C7-L239C53) has defined them.

The importance of these alerts is to ensure the high availability of these components by tracking the rate at which they are failing to meet their SLOs. This is assuming these components should be available and operational 99.95% of the time.

@astefanutti I'm very interested in your thoughts on this and/or changes to be made? Thanks in advance.

**Comment by ChristianZaccaria** [comment]
Moved to here: https://github.com/red-hat-data-services/odh-deployer/pull/380

**Pull request closed without merging**
