### PR TITLE
Remove Seldon from the dashboard (rebased to 1.19 version)

### PR DESCRIPTION
**Pull request by Xaenalt**
Remove Seldon backend files from the dashboard

Ensure Seldon dashboard resources are deleted on upgrade

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [X] JIRA link(s): https://issues.redhat.com/browse/RHODS-5946
- [X] The Jira story is acked.
- [X] Live build image: 
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work.
- [X] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Comment by Xaenalt** [comment]
Livebuild link https://rhods-jenkins-csb-livebuilds.apps.ocp-c1.prod.psi.redhat.com/job/rhods-livebuild/259

**Comment by cfchase** [comment]
New live build quay.io/cfchase/rhods-operator-live-catalog:1.19.0-rhods-5946

**Review by cfchase — APPROVED** [review]
/lgtm

tested upgrade @Jooho tested clean install

**Review by anishasthana — APPROVED** [review]
/lgtm

**Pull request merged**
