### PR TITLE
Alert only on new builds that are failing

### PR DESCRIPTION
**Pull request by maulikjs**
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-2051
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).

### CODE REVIEW

**Comment by maulikjs** [comment]
@sugarraysam can you PTAL?

**Comment by sugarraysam** [comment]
LGTM

**Comment by anishasthana** [comment]
I can confirm that the alert looks correct after upgrade.
I wasn't sure how to test it out, however

**Review by crobby — COMMENTED** [review]
Changes appear good to me, but I am also not sure how to experience them.
If an expert agrees that this is good to go, I approve.

**Comment by lucferbux** [comment]
/lgtm
I've tested it, and it stop the alert after 10 minutes.

**Review by lucferbux — APPROVED** [review]

**Comment by anishasthana** [comment]
@maulikjs Can you add an entry to the build announcement document?

**Comment by maulikjs** [comment]
@anishasthana done

**Review by anishasthana — APPROVED** [review]

**Pull request merged**
