### PR TITLE
Add Parameters for Notebook Images

### PR DESCRIPTION
**Pull request by VaishnaviHire**
## Description
This is a follow-up PR for following changes:
- https://github.com/red-hat-data-services/odh-manifests/pull/332
- https://gitlab.cee.redhat.com/data-hub/rhods-live-builder/-/merge_requests/178#587d266bb27a4dc3022bbed44dfa19849df3044c

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [ ] JIRA link(s): https://issues.redhat.com/browse/RHODS-7422
- [ ] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
/hold

This is blocked by https://github.com/red-hat-data-services/odh-manifests/pull/332

**Comment by atheo89** [comment]
/remove-lgtm since the RELATED_IMAGES_* refered to the cpass. On the notebooks case won't work due to the fact are store in quay registry

**Comment by zdtsw** [comment]
can we double check if this PR still required and update linked  Jira ticket?

**Comment by VaishnaviHire** [comment]
Hi @zdtsw , closing this since its no longer required. @atheo89 has setup a workflow to update the env variables directly

**Pull request closed without merging**
