### PR TITLE
Remove Seldon from the dashboard

### PR DESCRIPTION
**Pull request by Xaenalt**
Fixes [RHODS-5946](https://issues.redhat.com//browse/RHODS-5946)

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [X] JIRA link(s):
- [X] The Jira story is acked.
- [X] Live build image: 
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work.
- [X] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Review by bdattoma — APPROVED** [review]

**Review by pablofelix — APPROVED** [review]
/lgtm

**Review by anishasthana — APPROVED** [review]
/approve /qe-approved 

(This is due to JooHo and Pablo both approving the PR)

**Comment by Xaenalt** [comment]
https://rhods-jenkins-csb-livebuilds.apps.ocp-c1.prod.psi.redhat.com/job/rhods-livebuild/256 is the livebuild link

**Comment by Jooho** [comment]
Tested the live builder image and confirm the seldon contents are removed from ODH Dashboard Resources.

**Comment by Xaenalt** [comment]
New livebuild link https://rhods-jenkins-csb-livebuilds.apps.ocp-c1.prod.psi.redhat.com/job/rhods-livebuild/258/

**Comment by cfchase** [comment]
Should this be targeting the [rhods-1.19](https://github.com/red-hat-data-services/odh-deployer/tree/rhods-1.19) branch?

**Comment by Xaenalt** [comment]
Superceded by https://github.com/red-hat-data-services/odh-deployer/pull/283

**Pull request closed without merging**
