### PR TITLE
Add artifacts required for RHODS notebook deployment to custom namespace

### PR DESCRIPTION
**Pull request by anishasthana**
Relevant JIRA: https://issues.redhat.com/browse/RHODS-1520
Related PR: https://github.com/red-hat-data-services/odh-manifests/pull/127

Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

### CODE REVIEW

**Review by crobby — CHANGES_REQUESTED** [review]
Fails because Dockerfile needs to copy the new yaml to the image

**Comment by anishasthana** [comment]
@tmckayus This PR updates the dockerfile as well

**Review by crobby — APPROVED** [review]
I have tested this locally along with https://github.com/red-hat-data-services/odh-manifests/pull/127 (which needs to get merged before this...along with the updated to opendatahub-operator/odh-manifests).

**Comment by anishasthana** [comment]
opendatahub-operator has been updated as part of https://github.com/red-hat-data-services/opendatahub-operator/pull/73. Merging now.

**Pull request merged**
