### PR TITLE
Update CRO v0.39

### PR DESCRIPTION
**Pull request by lucferbux**
- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)
- [x] The developer has manually tested the changes and verified that the changes work.

## Live build

quay.io/lferrnan/rhods-operator-live-catalog:1.12.2-update-cro

## Testing instructions
1. Create a new deployment in OSD
2. Install this version
3. Check if the CRO installed is the v0.39

### CODE REVIEW

**Comment by lucferbux** [comment]
Screenshot 2022-06-08 at 13 32 13

**Review by crobby — APPROVED** [review]
lgtm

**Review by anishasthana — CHANGES_REQUESTED** [review]
I don't think we can give read access to all secrets on the cluster. @lucferbux can you figure out how to scope this to fewer namespaces?

**Comment by lucferbux** [comment]
> I don't think we can give read access to all secrets on the cluster. @lucferbux can you figure out how to scope this to fewer namespaces?

Yes! I was trying to change it yesterday, I'll ping you back once I got it.

**Review by anishasthana — APPROVED** [review]
I'm seeing the expected CRO version, role, and rolebinding in the deployment.
/lgtm (pending QE +1, that is :-) )

**Pull request merged**
