### PR TITLE
Enable tls

### PR DESCRIPTION
**Pull request by anishasthana**
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-1993
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Comment by anishasthana** [comment]
Looks like the grafana secret does _not_ get updated to enable TLS when we upgrade. 

This is due to the following
```
oc create -n $ODH_MONITORING_PROJECT -f monitoring/grafana/grafana-secrets.yaml || echo "INFO: Grafana secrets already exist."
```

I'm not quite sure what we can/should do here.

**Comment by anishasthana** [comment]
I've updated the logic to account for upgrades. It works correctly on both fresh installs and upgrades.

**Comment by anishasthana** [comment]
image
Note the lack of tlsSkipVerify :-)

**Comment by anishasthana** [comment]
This is only to be merged in for the 1.3.0 release

**Comment by anishasthana** [comment]
@crobby @maulikjs please review!

**Review by crobby — APPROVED** [review]
Tested with:  quay.io/modh/rhods-operator-live-catalog:1.3.0-rhods-1993
lgtm

**Pull request merged**
