### PR TITLE
Added segment key secret

### PR DESCRIPTION
**Pull request by lucferbux**
## Checks

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-871
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

## Testing instructions

1. Deploy this changes into a cluster
2. Open the RHODS Dashboard and navigate through some sections
3. Check in Segment.io that those interactions are tracked

### CODE REVIEW

**Comment by anishasthana** [comment]
We can't merge this PR yet

**Comment by gmfrasca** [comment]
does this get automatically applied or do we need to update the deployment script?

**Review by crobby — COMMENTED** [review]
Does this wind-up getting applied by something?

**Comment by lucferbux** [comment]
> Does this wind-up getting applied by something?

nope, I missed applying it in the script, thanks @crobby !

**Comment by jgarciao** [comment]
@lucferbux I'm not sure, but it's possible RHODS-658 have to be finished before merging this

**Comment by lucferbux** [comment]
> @lucferbux I'm not sure, but it's possible RHODS-658 have to be finished before merging this

Yeah, I'm gonna discuss it with my team, because I'm not 100% sure but it makes sense. Either way, RHODS-658 is still an Spike, so I'm not sure if the task would be done once we figure out what to do with the onboarding.

**Pull request closed without merging**
