### PR TITLE
Update Grafana to 7.5.9

### PR DESCRIPTION
**Pull request by anishasthana**
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-2526
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)

### CODE REVIEW

**Comment by anishasthana** [comment]
This should not be merged until the 1.7 build is in the works

**Comment by samuelvl** [comment]
Creating a live build image to test this change

**Comment by samuelvl** [comment]
lgtm

Tested with image `quay.io/modh/rhods-operator-live-catalog:1.7.0-rhods-2526` 

```
$ curl ${grafana_url}/api/health
{
  "commit": "NA",
  "database": "ok",
  "version": "7.5.9"
}

**Review by samuelvl — APPROVED** [review]

**Pull request merged**
