### PR TITLE
Advertise TensorFlow support in OVMS 2022.3+

### PR DESCRIPTION
**Pull request by Xaenalt**
Adds the tag to the servingruntime to show TF support

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [X] JIRA link(s): https://issues.redhat.com/browse/RHODS-8874
- [X] The Jira story is acked.
- [X] Live build image: 
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work.
- [X] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Comment by Xaenalt** [comment]
s/ONNX/OVMS/ but yes, this should be there ootb

**Comment by lucferbux** [comment]
> s/ONNX/OVMS/ but yes, this should be there ootb

Perfect, I'm adding it too, thanks!

**Comment by lucferbux** [comment]
wait, @Xaenalt I'm changing the name of the files in https://github.com/red-hat-data-services/odh-deployer/pull/340/files
Would you mind to close this issue and I'll add tensorflow in my prs?

**Comment by lucferbux** [comment]
Added in this commit: https://github.com/red-hat-data-services/odh-deployer/pull/340/commits/fe33221e4e034359469c211c92355d1f035922e8

**Comment by Xaenalt** [comment]
Closing as superceded by https://github.com/red-hat-data-services/odh-deployer/pull/340

**Pull request closed without merging**
