### PR TITLE
Adding needed ports to ingress rule for non-OSD installs on OCP 4.10

### PR DESCRIPTION
**Pull request by crobby**
- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [x] JIRA link(s): https://issues.redhat.com/browse/RHODS-3178
- [x] The Jira story is acked
- [x] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)
- [x] The developer has manually tested the changes and verified that the changes work.

### CODE REVIEW

**Comment by crobby** [comment]
hold for now since it's not acked yet

**Comment by crobby** [comment]
live image build in-flight

**Comment by VaishnaviHire** [comment]
> live image build in-flight

Is the live build available ?

**Comment by crobby** [comment]
> > live image build in-flight
> 
> Is the live build available ?

Sorry...got distracted...firing off build now...for real.

**Comment by crobby** [comment]
> > live image build in-flight
> 
> Is the live build available ?

Live build is:  quay.io/croberts/rhods-operator-live-catalog:1.8.0-0-jira-3178

**Comment by VaishnaviHire** [comment]
/lgtm

Worked well for me on a PSI cluster.

**Review by VaishnaviHire — APPROVED** [review]

**Pull request merged**
