### PR TITLE
Remove RHOSAK

### PR DESCRIPTION
**Pull request by andrewballantyne**
https://issues.redhat.com/browse/RHODS-8275

### CODE REVIEW

**Review by lucferbux — APPROVED** [review]
/lgtm

**Comment by andrewballantyne** [comment]
@bdattoma need a QE approval here -- I saw you made a comment on the RHODS ticket, so I figure I'll tag you here.

**Comment by bdattoma** [comment]
> @bdattoma need a QE approval here -- I saw you made a comment on the RHODS ticket, so I figure I'll tag you here.

A question: is the `rhosak-validation-result` automatically created by deploying `odh-dashboard/apps-on-prem/rhosak/rhosak-app.yaml`?

**Comment by andrewballantyne** [comment]
> > @bdattoma need a QE approval here -- I saw you made a comment on the RHODS ticket, so I figure I'll tag you here.
> 
> A question: is the `rhosak-validation-result` automatically created by deploying `odh-dashboard/apps-on-prem/rhosak/rhosak-app.yaml`?

I have no idea -- @lucferbux ? 

I'm only the author of this PR because everyone was standing around pointing fingers at each other like the Spiderman meme. I have no knowledge on anything here, I just deleted the resources as they were labeled RHOSAK. Can't deploy RHOSAK if there are no resources to deploy.

**Comment by lucferbux** [comment]
> > > @bdattoma need a QE approval here -- I saw you made a comment on the RHODS ticket, so I figure I'll tag you here.
> > 
> > 
> > A question: is the `rhosak-validation-result` automatically created by deploying `odh-dashboard/apps-on-prem/rhosak/rhosak-app.yaml`?
> 
> I have no idea -- @lucferbux ?
> 
> I'm only the author of this PR because everyone was standing around pointing fingers at each other like the Spiderman meme. I have no knowledge on anything here, I just deleted the resources as they were labeled RHOSAK. Can't deploy RHOSAK if there are no resources to deploy.

No idea either, I don't see that file deployed anywhere and I don't have any context about it, not sure how or where is used.

**Comment by bdattoma** [comment]
> > > > @bdattoma need a QE approval here -- I saw you made a comment on the RHODS ticket, so I figure I'll tag you here.
> > > 
> > > 
> > > A question: is the `rhosak-validation-result` automatically created by deploying `odh-dashboard/apps-on-prem/rhosak/rhosak-app.yaml`?
> > 
> > 
> > I have no idea -- @lucferbux ?
> > I'm only the author of this PR because everyone was standing around pointing fingers at each other like the Spiderman meme. I have no knowledge on anything here, I just deleted the resources as they were labeled RHOSAK. Can't deploy RHOSAK if there are no resources to deploy.
> 
> No idea either, I don't see that file deployed anywhere and I don't have any context about it, not sure how or where is used.

I did a try creating a custom tile in the dashboard (i.e., OdhApplication object) with the enablement flow. It creates the config map automatically after clicking on "Enable" button in Explore page.

This is the app definition I used, in case you wanna give a try yourselves:

```
apiVersion: dashboard.opendatahub.io/v1
kind: OdhApplication
metadata:
  labels:
    app: custom-odsci-app
  name: custom-odsci-app
  namespace: redhat-ods-applications
spec:
  enable:
    actionLabel: Enable
    description: Clicking enable will add a card to the Enabled page
    link: 'https://github.com/red-hat-data-services/ods-ci'
    linkPreface: 'Before enabling, be sure you can access:'
    title: Enable Custom ODS-CI App
    validationConfigMap: odsci-validation-result
  img: "image_path_or_svg"
  getStartedLink: 'https://github.com/red-hat-data-services/ods-ci'
  displayName: TEST - Custom ODS-CI Application
  kfdefApplications: []
  support: redhat
  csvName: custom-odsci-app
  provider: ods-ci
  docsLink: 'https://github.com/red-hat-data-services/ods-ci'
  getStartedMarkDown: >-
    # ODS-CI

    ## Your RHODS Tester...Robotic! Develop automated tests for verifying
    functioning of RHODS

    ODS-CI is available on GitHub ### Subscribe to the operator on Marketplace -
    [https://github.com/red-hat-data-services/ods-ci](https://github.com/red-hat-data-services/ods-ci)
  description: >-
    Custom Application is a test item created by ODS-CI to test creation of
    custom doc resources.
  category: Red Hat managed
```

**Comment by andrewballantyne** [comment]
If there is a configmap created by the effort -- we'd need some build upgrade script to delete it. I'm not in the business of writing scripts to delete resources on a customer cluster.

@bdattoma please reply on the ticket and tag Jeff.

Pretty sure we want these resources gone, the unused configmap *should* be cleaned up by us in some fashion -- but that's really not for this PR.

**Review by bdattoma — APPROVED** [review]

**Comment by andrewballantyne** [comment]
Added the label based on Berto approving.

**Pull request merged**
