### PR TITLE
Use sha images for all dspo images. (#321)

### PR DESCRIPTION
**Pull request by HumairAK**
From: https://github.com/red-hat-data-services/odh-deployer/pull/321

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve
thanks :100:

**Comment by HumairAK** [comment]
> /cherry-pick rhods-1.26 

@VaishnaviHire this is cherry picked manually I guess, is the preferred way to use this command on the pr to main branch?

**Pull request merged**
