### PR TITLE
Modify Approver List

### PR DESCRIPTION
**Pull request by lucferbux**
## Description

Remove QE from the list of approvals in order to merge the PR

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message.
- [ ] JIRA link(s):
- [ ] The Jira story is acked.
- [ ] Live build image: 
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work.
- [ ] QE contact acknowledges that this has been tested and is approved for merge.

### CODE REVIEW

**Comment by zdtsw** [comment]
https://github.com/red-hat-data-services/odh-deployer/blame/main/CONTRIBUTING.md#L67
https://github.com/red-hat-data-services/odh-deployer/blame/main/CONTRIBUTING.md#L27
need updates too

**Comment by lucferbux** [comment]
@Jooho I've added you to the list too

**Comment by zdtsw** [comment]
> @Jooho I've added you to the list too

hmmmmmmmmmm, could not see jooho in the change list.

**Comment by andrewballantyne** [comment]
@lucferbux did you forget to push your commit?

**Comment by lucferbux** [comment]
> @lucferbux did you forget to push your commit?

Agh, yes, I ammended the commit and did a quick push, forget to force it.

Give me 15 mins, i had to go out, once im back ill push it for good.

**Comment by lucferbux** [comment]
@andrewballantyne done!

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Comment by lucferbux** [comment]
@VaishnaviHire I'm sorry i added an extra end line, can you approve it again 😅

**Review by VaishnaviHire — APPROVED** [review]
/lgtm

**Comment by andrewballantyne** [comment]
@lucferbux hah, QE has to approve the removal of QE? The thread lead me to believe this was a dev decision... can you manually add the label?

**Pull request merged**
