### PR TITLE
Point tensorflow and pythorch builds to rhds repositories

### PR DESCRIPTION
**Pull request by tmckayus**

### CODE REVIEW

**Comment by tmckayus** [comment]
This is the first step in getting consistency across notebook packages in install-time builds

**Comment by tmckayus** [comment]
@crobby @anishasthana ptal

**Comment by tmckayus** [comment]
Added the python38 branch to s2i-minimal-notebook repo in red-hat-data-services. Note that this is different than the v1.0.0 branch -- it's meant to be just a mirror of upstream thoth-station with a modified Pipfile.

**Review by anishasthana — APPROVED** [review]
Changes look good to me.

**Review by crobby — APPROVED** [review]

**Pull request merged**
