### PR TITLE
Add a custom CM to allow an admin to control JH global profile

### PR DESCRIPTION
**Pull request by LaVLaS**
This will update add a custom JH singleuserprofile that a RHODS admin can modify without the operator making resetting it during reconciliation

RHODS Jira: [1524](https://github.com/red-hat-data-services/odh-deployer/pull/125)

Signed-off-by: Landon LaSmith <LLaSmith@redhat.com>

### CODE REVIEW

**Comment by maulikjs** [comment]
@LaVLaS is this still a WIP?

**Comment by LaVLaS** [comment]
> @LaVLaS is this still a WIP?

I forgot about this PR. I just updated the PR to make this change

**Review by maulikjs — APPROVED** [review]

**Review by anishasthana — CHANGES_REQUESTED** [review]
Can you rebse on main?

**Comment by LaVLaS** [comment]
> Can you rebse on main?

Done

**Review by anishasthana — APPROVED** [review]

**Pull request closed without merging**
